routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Handbook\SectionController;
use App\Http\Controllers\Handbook\GenderController;
use App\Http\Controllers\Handbook\StatusController;
use App\Http\Controllers\Handbook\PositionController;
use App\Http\Controllers\Fullcalendar\FullCalendarController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

Route::get('/register', [RegisterController::class, 'showRegistrationForm'])->name('register');
Route::post('/register', [RegisterController::class, 'register']);

Route::middleware('auth')->group(function () {

    Route::resource('/users', UserController::class)->middleware('role:admin');

    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('/sections', SectionController::class);
    Route::resource('/genders', GenderController::class);
    Route::resource('/statuses', StatusController::class);
    Route::resource('/positions', PositionController::class);
    
    Route::resource('/calendars', FullCalendarController::class );
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{

    use LaratrustUserTrait;
    use HasFactory, Notifiable;

    protected $table = 'users';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'gender_id',
        'position_id',
        'section_id',
        'status_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'created_at' => 'date:d.m.y',
        'updated_at' => 'date:d.m.y',
    ];

    public function setPasswordAttribute($pass)
    {
        $this->attributes['password'] = Hash::make($pass);
    }

    public function gender()
    {
        return $this->belongsTo('App\Models\Gender');
    }

    public function position()
    {
        return $this->belongsTo('App\Models\Position');
    }

    public function section()
    {
        return $this->belongsTo('App\Models\Section');
    }

    public function status()
    {
        return $this->belongsTo('App\Models\Status');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UserRequest;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Role;
use App\Models\Gender;
use App\Models\Position;
use App\Models\Section;
use App\Models\Status;
use Yajra\DataTables\Html\Builder;

use DataTables;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function index(Request $request, Builder $builder, User $user)
    {
        if ($request->ajax()) {

            $data = User::with(['gender', 'status', 'section', 'position', 'roles']);

            return DataTables::of($data)
                ->addColumn('action', function ($data) {
                    return view('users.buttons', compact('data'));
                })
                ->addColumn('roles', function ($user) {
                    return $user->roles->map(function ($role) {
                        return $role->display_name;
                    })->implode('<br>');
                })

                ->rawColumns(['action'])
                ->make(true);
        }

        $builder->columns([
            ['data' => 'id', 'name' => 'id', 'title' => '№', 'style' => 'width:  100px'],
            ['data' => 'name', 'name' => 'name', 'title' => 'Имя', 'style' => 'width: 100px'],
            ['data' => 'email', 'name' => 'email', 'title' => 'Почта'],
            ['data' => 'roles', 'name' => 'roles', 'title' => 'Права', 'style' => 'width: 100px'],
            ['data' => 'section.title', 'name' => 'section.title', 'title' => 'Отдел', 'style' => 'width: 100px'],
            ['data' => 'position.title', 'name' => 'position.title', 'title' => 'Должность', 'style' => 'width: 100px'],
            ['data' => 'gender.title', 'name' => 'gender.title', 'title' => 'Пол', 'style' => 'width: 100px'],
            ['data' => 'status.title', 'name' => 'status.title', 'title' => 'Статус', 'style' => 'width: 100px'],
            ['data' => 'action', 'name' => 'action', 'title' => 'Действие', 'style' => 'width: 50px'],
        ])->parameters([
            'language' => [
                'url' => url('vendor/datatables/js/lang-ru.json')
            ]
        ]);

        return view('users.index', compact('builder'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::pluck('name', 'id');
        $genders = Gender::get();
        $positions = Position::get();
        $statuses = Status::get();
        $sections = Section::get();

        return view('users.create', compact('roles', 'genders', 'positions', 'statuses', 'sections'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(User $user, CreateUserRequest $request)
    {
        $requestAll = $request->all();
        $userCreate = $user->create($requestAll);
        $userCreate->attachRole($request->role);
        flash(__('user.create'))->success();
        return redirect()->route('users.index')->with('success', trans('user.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roleId = $user->roles->pluck('id');
        $roles = Role::pluck('name', 'id');
        $genders = Gender::get();
        $positions = Position::get();
        $statuses = Status::get();
        $sections = Section::get();

        return view('users.edit', compact('user', 'roleId', 'roles', 'genders', 'positions', 'statuses', 'sections'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function update(UserRequest $request, User $user)
    {
        $requestAll = $request->all();
        if ($request->password == null) {
            unset($requestAll['password']);
        }
        $user->update($requestAll);
        $user->roles()->sync($request->role);
        flash(__('user.create'))->success();
        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return response()->json(['status' => 'success']);
    }
}

resources/views/users/buttons.blade.php
<div class="d-flex justify-content-end">
    <a href="{{ route('users.edit', $data->id) }}" class="btn btn-outline-info btn-m rounded-circle btn-sm mx-2"><i
            class="fas fa-pencil-alt"></i></a>

    <button type="button" class="btn btn btn-outline-danger btn-m rounded-circle btn-sm mx-2"
        onclick="delPerson(`{{route('users.destroy', $data->id) }}`)"><i class="fas fa-trash-alt"></i></button>
</div>

resources/views/users/create.blade.php
@extends('adminlte::page')

@section('content')
    <div class="col-md-12 mt-1">
        <div class="card card-success">
            <div class="card-header">
                <h3 class="card-title">Добавить сотрудника</h3>
            </div>
            <div class="card-body">
                <form action="{{ route('users.store') }}" method="POST">
                    @csrf
                    @method('POST')

                    <div class="form-group">
                        <label for="name_person">Имя</label>
                        <input type="text" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" name="name"
                            value="{{ old('name') }}" placeholder="Введите имя">
                        @error('name')
                            <span class="error invalid-feedback">{{ $message }}</span>
                        @enderror

                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}"
                            name=" email" value="{{ old('email') }}" aria-describedby="emailHelp"
                            placeholder="Введите Email">
                        @error('email')
                            <span class="error invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="exampleInputPassword">Пароль</label>
                        <input type="password" class="form-control {{ $errors->has('password') ? 'is-invalid' : '' }}"
                            name="password" placeholder="Введите пароль">
                        @error('password')
                            <span class="error invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group mb-3 mt-5">
                        <label>Права</label>
                        <select class="custom-select {{ $errors->has('role') ? 'is-invalid' : '' }}" name="role">
                            <option value="null" selected>Права доступа</option>
                            @foreach ($roles as $key => $value)
                                <option value="{{ $key }}">{{ $value }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group mb-3">
                        <label>Пол </label>
                        <select class="custom-select {{ $errors->has('gender') ? 'is-invalid' : '' }}" name="gender_id">
                            <option value="null" selected>Выберите пол</option>
                            @foreach ($genders as $gender)
                                <option value="{{ $gender->id }}">{{ $gender->title }}</option>
                            @endforeach

                        </select>
                    </div>

                    <div class="form-group mb-3">
                        <label>Должность </label>
                        <select class="custom-select {{ $errors->has('position') ? 'is-invalid' : '' }}"
                            name="position_id">
                            <option value="null" selected>Выберите должность</option>
                            @foreach ($positions as $position)
                                <option value="{{ $position->id }}">{{ $position->title }}</option>
                            @endforeach

                        </select>
                    </div>

                    <div class="form-group mb-3">
                        <label>Отдел</label>
                        <select class="custom-select {{ $errors->has('section') ? 'is-invalid' : '' }}"
                            name="section_id">
                            <option value="null" selected>Выберите отдел</option>
                            @foreach ($sections as $section)
                                <option value="{{ $section->id }}">{{ $section->title }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group mb-3">
                        <label>Статус</label>
                        <select class="custom-select {{ $errors->has('status') ? 'is-invalid' : '' }}" name="status_id">
                            <option value="null" selected>Выберите статус</option>
                            @foreach ($statuses as $status)
                                <option value="{{ $status->id }} "> {{ $status->title }} </option>
                            @endforeach
                        </select>
                    </div>

            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success">Добавить</button>
            </div>

            </form>
        </div>
    </div>
    </div>

@endsection

resources/views/users/edit.blade.php
@extends('adminlte::page')

@section('content')
    <div class=" col-md-12">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Редактировать</h3>
            </div>
            <form action="{{ route('users.update', $user->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">

                    <div class="form-group">
                        <label for="name">Изменить имя</label>
                        <input type="text" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" name="name"
                            value="{{ old('name', optional($user)->name) }}">
                        @error('name')
                            <span class="error invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label>Изменить email</label>
                        <input type="email" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}"
                            name="email" value="{{ old('email', optional($user)->email) }}">
                        @error('email')
                            <span class="error invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label>Пароль</label>
                        <input type="password" class="form-control {{ $errors->has('password') ? 'is-invalid' : '' }}"
                            name="password" placeholder="Введите пароль">
                        @error('password')
                            <span class="error invalid-feedback">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group mb-3 mt-5">
                        <label>Права</label>
                        <select class="custom-select {{ $errors->has('role') ? 'is-invalid' : '' }}" name="role">
                            @foreach ($roles as $key => $value)
                                <option @if ($roleId->contains($key)) selected @endif value="{{ $key }}">{{ $value }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group mb-3">
                        <label>Пол </label>
                        <select class="custom-select {{ $errors->has('gender') ? 'is-invalid' : '' }}" name="gender_id">
                            @foreach ($genders as $gender)
                                <option @if ($gender->id == $user->gender_id) selected @endif value="{{ $gender->id }}">{{ $gender->title }}</option>
                            @endforeach

                        </select>
                    </div>

                    <div class="form-group mb-3">
                        <label>Должность </label>
                        <select class="custom-select {{ $errors->has('position') ? 'is-invalid' : '' }}"
                            name="position_id">
                            @foreach ($positions as $position)
                                <option @if ($position->id == $user->position_id) selected @endif value="{{ $position->id }}">
                                    {{ $position->title }}</option>
                            @endforeach

                        </select>
                    </div>

                    <div class="form-group mb-3">
                        <label>Отдел</label>
                        <select class="custom-select {{ $errors->has('section') ? 'is-invalid' : '' }}"
                            name="section_id">
                            @foreach ($sections as $section)
                                <option @if ($section->id == $user->section_id) selected @endif value="{{ $section->id }}">{{ $section->title }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group mb-3">
                        <label>Статус</label>
                        <select class="custom-select {{ $errors->has('status') ? 'is-invalid' : '' }}" name="status_id">
                            @foreach ($statuses as $status)
                                <option @if ($status->id == $user->status_id) selected @endif value="{{ $status->id }} "> {{ $status->title }} </option>
                            @endforeach
                        </select>
                    </div>

                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Изменить</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('adminlte::page')

@section('content_header')
    <div class="d-flex">
        <h1>Сотрудники</h1>
        <a href="{{ route('users.create') }}" class="btn btn-outline-primary rounded btn mx-3"><i
                class="fas fa-plus-square"></i></a>
    </div>
@stop

@section('content')
    @include('flash::message')
    <div class="card">
        <div class="card-body">
            <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                {!! $builder->table(['class' => 'table table-bordered table-striped dataTable dtr-inline']) !!}
            </div>
        </div>
    </div>
    
@endsection

@push('js')
    {!! $builder->scripts() !!}
    <script>
        function delPerson(deleteUser) {
            console.log(deleteUser);
            $.ajax({
                type: 'DELETE',
                url: deleteUser,
                data: {
                    _token: $("input[name=_token]").val()
                },
                success: function(res) {
                    if (res['status'] == 'success') {
                        LaravelDataTables.dataTableBuilder.ajax.reload();
                    }
                },
                error: function(err) {
                    console.log(err);
                }
            });
        }

    </script>
@endpush